fix: update configs types
gajus/eslint-plugin-jsdoc pull request #1344
Opened 2024-12-10 17:04 UTC by gurgelio

Not all config keys were included in the Record, only the recommended ones.

2024-12-10 23:30 UTC, brettz9 requested changes
Thanks... I think just the suggested nit fixes and we should be good to go here...

2024-12-10 23:30 UTC, brettz9 commented on src/index.js
> + * @typedef {"recommended" | "stylistic" | "contents" | "logical"} ConfigGrous
```suggestion
 * @typedef {"recommended" | "stylistic" | "contents" | "logical"} ConfigGroups
```

2024-12-10 23:30 UTC, brettz9 commented on src/index.js
> +*   configs: Record<`flat/${ConfigGrous}${ConfigVariants}${ErrorLevelVariants}`, import('eslint').Linter.Config>
```suggestion
*   configs: Record<`flat/${ConfigGroups}${ConfigVariants}${ErrorLevelVariants}`, import('eslint').Linter.Config>
```

2024-12-11 00:54 UTC, brettz9 commented on src/index.js
> +*   configs: Record<`flat/${ConfigGrous}${ConfigVariants}${ErrorLevelVariants}`, import('eslint').Linter.Config>
This change apparently wasn't committed.

2024-12-11 00:56 UTC, gurgelio commented
I've just fixed those typos

2024-12-11 00:57 UTC, brettz9 approved these changes

2024-12-11 00:58 UTC, merged

2024-12-11 00:59 UTC, brettz9 commented
Thanks for the PR!