Allow the use of jsx annotations
gajus/eslint-plugin-jsdoc pull request #702
Opened 2021-03-12 10:13 UTC by remcohaszing

These tags may be used to tweak how JSX is converted by Babel or TypeScript.

See https://babeljs.io/docs/en/babel-plugin-transform-react-jsx

2021-03-13 11:41 UTC, brettz9 commented
Hi,

I think it would be good to support this use case more conveniently, but I think it would probably be better as a new option to `check-tag-names` (like `jsxTags: true`) since part of the draw of the `check-tag-names` rule may be the ability to confine oneself to jsdoc standard tags (or Closure/TypeScript) only.

Another option could be adding it as a setting. This would allow its use by other rules, e.g., if you wanted our function `setTagStructure` to build the tag structure which, besides working for `check-tag-names`, could do checking for the validity of namepaths (or types) defined or referenced.

2021-03-14 12:29 UTC, brettz9 requested changes
Just a few minor doc tweaks, but otherwise LGTM...

2021-03-14 12:29 UTC, brettz9 commented on README.md
> +For more information, see the [babel documentation](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx)
```suggestion
For more information, see the [babel documentation](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx).
```

2021-03-14 12:29 UTC, brettz9 commented on .README/rules/check-tag-names.md
> +If this is set to `true`, tags used to control JSX output are allowed as all. This includes the the following tags:
```suggestion
If this is set to `true`, all of the following tags used to control JSX output are allowed:
```

2021-03-14 12:29 UTC, brettz9 commented on .README/rules/check-tag-names.md
> +For more information, see the [babel documentation](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx)
```suggestion
For more information, see the [babel documentation](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx).
```

2021-03-14 12:29 UTC, brettz9 commented on README.md
> +If this is set to `true`, tags used to control JSX output are allowed as all. This includes the the following tags:
```suggestion
If this is set to `true`, all of the following tags used to control JSX output are allowed:
```

2021-03-14 13:02 UTC, remcohaszing commented
Something weird happened when applying your suggestions :thinking: 

I’ve amended the suggestions manually instead and rebased.

2021-03-15 10:23 UTC, merged