fixerMessage for require-jsdoc
gajus/eslint-plugin-jsdoc pull request #766
Opened 2021-07-13 08:06 UTC by schmetzyannick

2021-07-13 08:07 UTC, schmetzyannick commented
Closes https://github.com/gajus/eslint-plugin-jsdoc/issues/764

2021-07-19 00:43 UTC, brettz9 requested changes
Looks good--just the `ignoreReadme`'s (and rebuilding the docs accordingly).

2021-07-19 00:43 UTC, brettz9 commented on test/rules/assertions/requireJsdoc.js
> +      ignoreReadme: true,
Notwithstanding the fact that we do need more `ignoreReadme` usage for some obscure edge cases, I think we actually want these examples to not be ignored as they demonstrate an option.

```suggestion
```

2021-07-19 00:43 UTC, brettz9 commented on test/rules/assertions/requireJsdoc.js
> +      ignoreReadme: true,
Likewise here...
```suggestion
```

2021-07-19 06:30 UTC, schmetzyannick commented
There was one more ignoreReadme line in the test, I removed them all.

2021-07-19 06:34 UTC, brettz9 commented
Ok, cool--and if you can run `npm run create-readme` to ensure the output README is updated accordingly...

2021-07-19 11:42 UTC, merged

2021-07-20 03:58 UTC, gajus commented
:tada: This PR is included in version 35.4.6 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/eslint-plugin-jsdoc/v/35.4.6)
- [GitHub release](https://github.com/gajus/eslint-plugin-jsdoc/releases/tag/v35.4.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: